#!/usr/bin/env python3
"""Generate tests/test-vectors/qwen.vec by running ds4 --dump-logprobs on
a set of reference prompts.  The output format matches official.vec so
 ds4_test.c can load it unchanged."""

import json
import subprocess
import sys
from pathlib import Path

DS4 = Path(__file__).parent.parent / "ds4"
MODEL = Path(__file__).parent.parent / "qwen3-coder.gguf"
OUT = Path(__file__).parent / "test-vectors" / "qwen.vec"

PROMPTS = [
    ("short_italian_fact", 16384, 4, "tests/test-vectors/prompts/short_italian_fact.txt"),
    ("short_code_completion", 4096, 4, "tests/test-vectors/prompts/short_code_completion.txt"),
    ("short_reasoning_plain", 4096, 1, "tests/test-vectors/prompts/short_reasoning_plain.txt"),
]


def bytes_to_hex(b: bytes) -> str:
    return b.hex()


def run_prompt(name: str, ctx: int, steps: int, prompt_path: str) -> list[dict]:
    dump = Path(f"/tmp/ds4_qwen_vec_{name}.json")
    cmd = [
        str(DS4),
        "-m", str(MODEL),
        "--ctx", str(ctx),
        "--prompt-file", prompt_path,
        "-n", str(steps),
        "--temp", "0",
        "--dump-logprobs", str(dump),
        "--logprobs-top-k", "20",
    ]
    print(f"[{name}] running ds4 ...", flush=True)
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    data = json.loads(dump.read_text())
    return data["steps"]


def main() -> int:
    if not DS4.exists():
        print(f"error: {DS4} not found", file=sys.stderr)
        return 1
    if not MODEL.exists():
        print(f"error: {MODEL} not found", file=sys.stderr)
        return 1

    lines = ["# ds4-qwen-logprob-vectors-v1", "# Generated by generate_qwen_vectors.py"]
    for name, ctx, steps, prompt_path in PROMPTS:
        try:
            step_data = run_prompt(name, ctx, steps, prompt_path)
        except subprocess.CalledProcessError as e:
            print(f"error running ds4 for {name}: {e}", file=sys.stderr)
            return 1

        lines.append(f"case {name} {ctx} {steps} {prompt_path}")
        for i, step in enumerate(step_data):
            selected = step["selected"]
            tops = step["top_logprobs"]
            # We store all returned top-k tokens; the test only checks up to 20
            ntop = min(len(tops), 20)
            lines.append(f"step {i} {bytes_to_hex(bytes(selected['bytes']))} {ntop}")
            for t in tops[:ntop]:
                token = t["token"]
                # logprob in the JSON is the raw logprob; we store it as-is
                lines.append(f"top {bytes_to_hex(bytes(token['bytes']))} {t['logprob']:.6g}")
        lines.append("end")
        print(f"[{name}] captured {len(step_data)} steps", flush=True)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
